version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: absensi_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: geo_presence
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: ./backend
    container_name: absensi_backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=geo_presence
      - JWT_SECRET=rahasiasangatbesar
      - PORT=8080
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: absensi_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always

volumes:
  pgdata: